### ISSUE TITLE
Cannot find module 'hydra-synth'

### ISSUE THREAD

**Issue by santiago-agoago** [hydra-synth/atom-hydra#50]
I am using MacOS Mojave 10.14.6 and have been unable to start hydra on atom. The error message is this:

Error: Cannot find module 'hydra-synth'
Require stack:
- /Users/ciutat/atom-hydra/atom-hydra/lib/main.js
- /Users/ciutat/atom-hydra/atom-hydra/lib/atom-hydra.js
- /Applications/Atom.app/Contents/Resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:157942)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149229)
    at Object.<anonymous> (/Users/ciutat/atom-hydra/lib/main.js:3:49)
    at Object.<anonymous> (/Users/ciutat/atom-hydra/lib/main.js:24:26)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149229)
    at Object.<anonymous> (/Users/ciutat/atom-hydra/lib/atom-hydra.js:7:15)
    at Object.<anonymous> (/Users/ciutat/atom-hydra/lib/atom-hydra.js:49:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:756278)
    at requireModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1175133)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3423763)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3411762)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1879
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1187666)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1189107)

Thank you!

**Comment by julianbejarano** [comment]
i have the same issue

**Comment by starmaid** [comment]
in your `atom-hydra` directory, try running `apm install`. That should install the dependencies, and should work after an atom restart. #54
