### ISSUE TITLE
Cannot find module 'hydra-synth' Require stack: [Atom-Windows 11]

### ISSUE THREAD

**Issue by CasaMa77a** [hydra-synth/atom-hydra#51]
Hi I am encountering this problem with atom-hydra,

Failed to activate the atom-hydra package

```
At Cannot find module 'hydra-synth'
Require stack:
- C:\Users\admin\atom-hydra\atom-hydra\lib\main.js
- C:\Users\admin\atom-hydra\atom-hydra\lib\atom-hydra.js
- C:\Users\admin\AppData\Local\atom\app-1.60.0\resources\app.asar\static\index.html

Error: Cannot find module 'hydra-synth'
Require stack:
- C:\Users\admin\atom-hydra\atom-hydra\lib\main.js
- C:\Users\admin\atom-hydra\atom-hydra\lib\atom-hydra.js
- C:\Users\admin\AppData\Local\atom\app-1.60.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:157942)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:149229)
    at Object.<anonymous> (~/atom-hydra/lib/main.js:3:49)
    at Object.<anonymous> (~/atom-hydra/lib/main.js:24:26)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:149229)
    at Object.<anonymous> (~/atom-hydra/lib/atom-hydra.js:7:15)
    at Object.<anonymous> (~/atom-hydra/lib/atom-hydra.js:49:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:1:802772)
    at requireModule (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:14:1175135)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:3543231)
    at Package.activateNow (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:3531230)
    at ~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:14:1879
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:1187666)
    at Emitter.emit (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:1189107)
```

### Commands

```
  4x -3:40.6.0 core:backspace (input.hidden-input)
  2x -3:38.8.0 editor:newline (input.hidden-input)
  3x -3:38.3.0 core:backspace (input.hidden-input)
     -3:33.6.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -3:14.3.0 atom-hydra:toggle (input.hidden-input)
  2x -3:07.3.0 core:backspace (input.hidden-input)
  2x -3:06.8.0 editor:newline (input.hidden-input)
     -3:03.7.0 intentions:highlight (input.hidden-input)
  3x -2:59.9.0 core:backspace (input.hidden-input)
  3x -2:59.5.0 intentions:highlight (input.hidden-input)
     -2:57 editor:newline (input.hidden-input)
     -2:56.2.0 intentions:highlight (input.hidden-input)
     -2:56 core:backspace (input.hidden-input)
     -2:55.8.0 intentions:highlight (input.hidden-input)
     -2:55.3.0 editor:newline (input.hidden-input)
  2x -2:55.2.0 intentions:highlight (input.hidden-input)
```

### Non-Core Packages

```
atom-hydra 0.4.3 
autocomplete-glsl 0.2.3 
busy-signal 2.0.1 
intentions 2.1.1 
language-glsl 2.0.4 
linter 3.4.0 
linter-glslify 1.0.0 
linter-ui-default 3.4.1 
tidalcycles 3.16.17 
veda 2.14.3 
```

**Comment by quatronostro** [comment]
I solved this problem with download ["hydra-synth" ](https://github.com/hydra-synth/atom-hydra). Just read the download instructions. 

But now I have another issue that is "Cannot use import statement outside a module" error. I searched and find [this website ](https://toastybits.dev/3-ways-to-fix-syntaxerror-cannot-use-import-statement-outside-a-module/)which is explain this problem step by step and tell you the solutions. But whatever I do it doesnt work, still same error.

**Comment by starmaid** [comment]
If you had previously installed atom-hydra through the atom GUI, try uninstalling it before doing the [instructions here](https://github.com/hydra-synth/atom-hydra#installing-atom-hydra-updated). That will make sure you are running the newest version of both atom-hydra and hydra-synth.

**Comment by jordan-ms** [comment]
If you added atom-hydra via `npm link`, you'll need to install it's package dependencies (which includes `hydra-synth`). Change into the `atom-hydra` directory and run `npm install`.
